version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_sections
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-sections:
    container_name: msvc-sections
    image: educacionta/sections
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATEBASE: msvc_sections
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      USER_URL: ec2-54-173-11-200.compute-1.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always
volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring